# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron: '0 */6 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          output="$(${GITHUB_WORKSPACE}/run.sh)"
          output="${output//$'\n'/'%0A'}"
          echo "::set-output name=tweet_status::$output"
        id: run_tracker

      - name: Send Tweet Action
        uses: ethomson/send-tweet-action@v1.0.0
        with:
          status: "${{ steps.run_tracker.outputs.tweet_status }}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
